title: Ploy N. Pratanwanich
author: Ploy N. Pratanwanich
email: naruemon.p[at]chula.ac.th
github_username: ploy-np
description: |
  Department of Mathematics and Computer Science
  Faculty of Science
  Chulalongkorn University
  Bangkok, 10330, Thailand
theme: minima
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed

